name: Generate reports

on:
  workflow_dispatch:
    inputs:
      questions:
        description: "Questions to generate (e.g. 1-20, 1,2,7, or 5)"
        required: true
        default: "1-20"
      study-group:
        description: "Study Group number"
        required: true
        default: "12"

jobs:
  generate_reports:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Generate reports
        run: |
          uv run rapporteur_helper \
            --questions "${{ inputs.questions }}" \
            --study-group "${{ inputs.study-group }}" \
            --verbose

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: status-reports-Q${{ inputs.questions }}-SG${{ inputs.study-group }}
          path: "**/*status_report.docx"
